login: &login
  username:
  password:
  adapter:  postgresql
  encoding: unicode
  host:     localhost
  pool:     10

development:
  username: cody
  database: eden_portfolio_development
  <<: *login

test:
  username: cody
  database: eden_portfolio_test
  <<: *login

production:
  <<: *login
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
