default: &default
  adapter: postgresql
  encoding: unicode
  username: cody
  password:
  pool: 5

development:
  <<: *default
  database: eden_portfolio_development

test:
  <<: *default
  database: eden_portfolio_test

production:
  <<: *default
  database: eden_portfolio_production
